import Head from 'next/head'
import HomeComponent from '@/components/Home/Home'
import { useSession } from 'next-auth/react'


export default function Home() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeComponent />
    </>
  )
}
